{
       "bomFormat": "CycloneDX",
       "specVersion": "1.4",
       "serialNumber": "urn:uuid:123e4567-e89b-12d3-a456-426614174000",
       "version": 1,
       "components": [
         {
           "type": "library",
           "name": "express",
           "version": "4.18.2",
           "group": "",
           "purl": "pkg:npm/express@4.18.2",
           "licenses": [
             {
               "license": {
                 "id": "MIT"
               }
             }
           ]
         },
         {
           "type": "library",
           "name": "jsonwebtoken",
           "version": "8.5.1",
           "group": "",
           "purl": "pkg:npm/jsonwebtoken@8.5.1",
           "licenses": [
             {
               "license": {
                 "id": "MIT"
               }
             }
           ]
         }
       ]
     }
